apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-07-13T20:28:58Z"
  labels:
    app: my-app
    owner: djkormo
  name: my-app
  namespace: my-app
  resourceVersion: "328590"
  selfLink: /api/v1/namespaces/my-app/services/my-app
  uid: 0e240429-bccc-41b1-9502-eada7ab0bb2a
spec:
  clusterIP: 10.108.147.213
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: my-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
