apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: "2021-07-13T20:20:03Z"
  generation: 5
  labels:
    app: my-app
    owner: djkormo
  name: my-app
  namespace: my-app
  resourceVersion: "329831"
  selfLink: /apis/apps/v1/namespaces/my-app/deployments/my-app
  uid: 0f17fd01-ed55-4ff1-8e9e-92cab72bef7e
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: my-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-app
    spec:
      containers:
      - env:
        - name: WHOAMI
          value: Kubernetes in 2021
        image: djkormo/primer
        imagePullPolicy: Always
        name: primer
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2021-07-13T20:27:36Z"
    lastUpdateTime: "2021-07-13T20:27:36Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-07-13T20:20:03Z"
    lastUpdateTime: "2021-07-13T20:39:36Z"
    message: ReplicaSet "my-app-7bd8bccbdb" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 5
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
